---
title: "Lecture2 Activity1: Binomial Test"
output:
  html_document: 
    toc: true
    toc_float: true
---
<br>

### Question 1

Let's say you are conducting a clinical trial to evaluate the effectiveness of a new drug in treating a specific medical condition. You have a group of 100 patients, and you want to determine if the drug has a higher success rate than the standard treatment. Out of the 100 patients, 75 showed improvement after receiving the new drug. You want to test if the proportion of successful outcomes is significantly different from the proportion expected under the null hypothesis (e.g., the success rate is the same as the standard treatment, which has a success rate of 60%).

a) What is the null & alternative hypothesis?

b) Please analyze the data. Does it appear as though there is a significant difference in the success rate between new and standard treatment?


<br>

<details>
  <summary><strong>Answer to Question 1:</strong></summary>
  
<br>

a) 
+ Null hypothesis: success rate is the same as the standard treatment ($\pi_{new}=0.6$).
+ Alternative hypothesis: success rate is different. ($\pi_{new} \ne 0.6$)


b) The two-sided binomial test yielded a p-value of 0.0021, indicating a significant difference in the proportion of successful outcomes between the new drug treatment and the standard treatment (60% success rate). In conclusion, the new drug treatment demonstrated a superior effectiveness compared to the standard treatment.

</details>
<br><br>

### Question 2

Suppose you are conducting a pre-clinical study to evaluate the effectiveness of a potential gene therapy treatment for a genetic disorder. In your experiment, you have a group of 50 mice that carry the genetic mutation associated with the disorder. You administer the gene therapy treatment to all 50 mice and monitor their response.

After a specified treatment period, you assess the presence or absence of symptoms in the mice. Out of the 50 treated mice, 40 show improvement and no longer exhibit symptoms associated with the disorder.

Please determine if the gene therapy treatment has a significant effect in reducing symptoms compared to the expected proportion. Our baseline is 50%.

<br>

<details>
  <summary><strong>Answer to Question 2:</strong></summary>
  
<br>

To perform a Fisher's exact test using Prism GraphPad:

1. Enter the data into the contingency table.
2. Select "Analyze" > "Compare observed distribution with expected."
3. In the "With two rows, perform" section, choose "Binomial test."
4. Please type in your expected #. (Success=25, Fail=25, in this case.)
5. The results of the binomial test are as follows:

+ P value: <0.0001 (significant at the alpha level of 0.05)
+ Conclusion: The binomial test showed a highly significant p-value (P<0.0001), indicating a substantial difference in the proportion of mice showing improvement after the gene therapy treatment compared to the expected proportion under the null hypothesis. It is evident that the gene therapy treatment was highly effective in reducing symptoms associated with the genetic disorder in the pre-clinical study.

</details>
<br><br>

<a href="schedule.html">< Go Back</a>
