---
title: "Lecture4 Activity2: ANOVA and Multiple Hypothesis Testing"
output:
  html_document: 
    toc: true
    toc_float: true
---
<br>

### Question 1: One-way ANOVA

In this experiment, the study endpoint involved measuring the thickness of mouse ears 96 hours after subjecting them to a fixed duration of UV radiation. The study hypothesis posits that mice receiving a specific dose of the supplement will exhibit reduced ear thickness compared to mice receiving normal food. Moreover, the effect of the supplement on ear thickness is expected to be more pronounced with higher doses.

You can download the data [HERE](files/lec4/earthickness.pzfx).

Is there a significant difference in ear thickness among the groups exposed to different doses of the supplement and the control group (mice receiving normal food) after 96 hours of UV radiation exposure? To test this, please perform a one-way ANOVA analysis on the data.

<br>

<details>
  <summary><strong>Answer to Question 1:</strong></summary>
  
<br>

The analysis of ear thickness among the groups exposed to different doses of the supplement and the control group (mice receiving normal food) after 96 hours of UV radiation exposure revealed significant findings. The F-value obtained was 6.012, with an associated p-value of 0.0013 (p < 0.05, **), indicating a statistically significant difference in ear thickness among the groups.

However, to determine precisely which groups exhibit significant differences, a post-hoc analysis is necessary due to the multiple hypothesis testing involved in the ANOVA result. The post-hoc analysis will allow us to conduct pairwise comparisons between the groups and identify specific group differences with appropriate statistical adjustments.

In conclusion, the data indicate a meaningful distinction in ear thickness between the experimental groups, but further analysis through post-hoc testing is required to identify the specific group differences and assess their significance.

</details>
<br><br>

### Question 2: Mutiple Hypothesis Testing (Post-hoc Analysis)

If the ANOVA results above indicate a significant difference in ear thickness among the groups, please conduct post-hoc analyses using Tukey's test to identify which specific groups exhibit statistically significant differences in ear thickness.

<br>

<details>
  <summary><strong>Answer to Question 2:</strong></summary>
  
  <br>
  
Tukey's multiple comparisons test revealed significant differences in ear thickness among the groups. Specifically, the NormalFood group showed significant differences with the MedDose (adj. p=0.0363) and HighDose (p=0.0006) groups. However, no significant differences were found between other dose comparisons. These results highlight the supplement's impact on ear thickness under UV radiation exposure.
  
<br>



</details>
<br><br>

<a href="schedule.html">< Go Back</a>
