---
title: "Lecture4 Activity1: Power Analysis and Correlation"
output:
  html_document: 
    toc: true
    toc_float: true
---
<br>


### Question 1. Power Analysis

Researchers are conducting a study to compare the tumor sizes between two groups of cancer patients who are receiving different treatments. The first group is receiving the standard treatment, while the second group is receiving an experimental treatment aimed at reducing tumor size. The researchers want to determine if the experimental treatment leads to a statistically significant reduction in tumor size compared to the standard treatment.

Based on previous studies, the researchers estimate that the standard deviation of tumor sizes is approximately 2.0 cm. They want to achieve a power of 80% (1-β = 0.80) with a significance level of 0.05 (α = 0.05).

The researchers expect the mean tumor size in the standard treatment group to be around 6.0 cm, while they anticipate a meaningful reduction in tumor size in the experimental treatment group, with a mean of 5.0 cm.

Please use the following [THIS](http://powerandsamplesize.com/) website to calculate the minimum sample size.

a. Calculate the minimum sample size required for each group to achieve the desired power of 80% with $\alpha = 0.05$.

b. What if the expected mean tumor size for the standard treatment group ($\mu_{standard}$) is now 7.0 cm? Calculate the minimum sample size required for each group to achieve the desired power of 80% with $\alpha = 0.05$. Does the required sample size increase or decrease?

c. What if the estimated standard deviation of tumor sizes is now 1.0 cm? Calculate the minimum sample size required for each group to achieve the desired power of 80% with $\alpha = 0.05$. Does the required sample size increase or decrease?

<br>

<details>
  <summary><strong>Answer to Question 1:</strong></summary>
  
<br>

a.

+ Group 'A' mean ($\mu_{A}$): 6
+ Group 'B' mean ($\mu_{B}$): 5
+ Standard Deviation ($\sigma$): 2
+ Sampling Ratio ($\kappa=n_{A} / n_{B}$): 1
+ Power ($1-\beta$): 0.8
+ Type I error rate ($\alpha$): 5%

To achieve 80% power at a 0.05 significance level, a minimum of 63 participants per group is required. Thus, at least 126 samples are needed (63 in each group).

<br>

b. 

+ Group 'A' mean ($\mu_{A}$): 7
+ Group 'B' mean ($\mu_{B}$): 5
+ Standard Deviation ($\sigma$): 2
+ Sampling Ratio ($\kappa=n_{A} / n_{B}$): 1
+ Power ($1-\beta$): 0.8
+ Type I error rate ($\alpha$): 5%

To achieve 80% power at a 0.05 significance level, a minimum of 16 participants per group is required. Thus, at least 32 samples are needed (32 in each group). 

The required sample size decreases as the expected mean tumor size for the standard treatment group increases.

<br>

c. 

+ Group 'A' mean ($\mu_{A}$): 6
+ Group 'B' mean ($\mu_{B}$): 5
+ Standard Deviation ($\sigma$): 1
+ Sampling Ratio ($\kappa=n_{A} / n_{B}$): 1
+ Power ($1-\beta$): 0.8
+ Type I error rate ($\alpha$): 5%

To achieve 80% power at a 0.05 significance level, a minimum of 16 participants per group is required. Thus, at least 32 samples are needed (32 in each group). 

The required sample size decreases as the estimated standard deviation of tumor sizes decreases.

</details>
<br><br>

### Question 2: Correlation

The dataset contains information from 50 breast cancer patients. For each patient, it includes the gene expression level of a specific oncogene and the corresponding tumor size in centimeters. Investigating the relationship between gene expression levels and tumor size in breast cancer patients.

You can download the dataset [HERE](files/lec4/oncogene.pzfx)
<br>

<details>
  <summary><strong>Answer to Question 2:</strong></summary>
  
<br>

The analysis of the dataset with 50 breast cancer patients shows a weak negative correlation (r = -0.2413) between gene expression levels and tumor size. However, this correlation is not statistically significant (P = 0.0914, not significant at alpha = 0.05).

</details>
<br><br>

<a href="schedule.html">< Go Back</a>
